# Generated by Django 4.2.23 on 2025-09-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_inmueble_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='imagen',
            field=models.ImageField(default='default-profile.avif', upload_to='foto_perfil/'),
        ),
    ]
